version: '3.5'

services:
  db: 
    container_name: marcospaulo-go-roach
    hostname: db
    image: cockroachdb/cockroach:v23.2.2
    command: start-single-node --insecure
    network_mode: "host"
    ports:
      - "26257:26257"
      - "8080:8080"
    #deploy:
#  resources:
#   limits:
#cpus: '0.5'
#memory: '200MB'

  nginx: # Load Balancer
    container_name: marcospaulo-go-nginx
    image: nginx:latest
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    #depends_on:
      #  - api1
      #  - api2
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '70MB'
  redis:
    container_name: marcospaulo-go-redis
    image: 'bitnami/redis:latest'
    network_mode: "host"
    #deploy:
#resources:
#limits:
#cpus: "0.2"
#memory: "40MB"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
